[package]
name = "frork-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "frork"
path = "src/main.rs"

[dependencies]
frork-lib = { path = "../frork-lib" }
miette = { version = "*", features = ["fancy"] }
fs-err = "*"
clap = { version = "*", features = ["derive", "env"] }
clap_complete = "*"
mlua = { version = "*", features = ["lua54", "serde", "vendored"] }
regex = "*"
serde = { version = "*", features = ["derive"] }
thiserror = "*"
tracing = "*"
tracing-subscriber = { version = "*", features = ["env-filter"] }

[dev-dependencies]
assert_cmd = "*"
predicates = "*"
hegeltest = "*"
tempfile = "*"

[lints.clippy]
self_named_module_files = "warn"
unwrap_used = "warn"
expect_used = "warn"
panic = "warn"
indexing_slicing = "warn"
arithmetic_side_effects = "warn"
